import { Search, UsersRound } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { subscribeDepartmentUsers, subscribeTodayAttendance } from '../services/attendance'
import { formatTime, humanDuration, minutesBetween } from '../utils/date'
import StatusBadge from '../components/StatusBadge'

export default function Department() {
  const { profile } = useAuth(); const [people,setPeople]=useState([]); const [attendance,setAttendance]=useState([]); const [search,setSearch]=useState('')
  useEffect(()=>{if(!profile?.department)return; const a=subscribeDepartmentUsers(profile.department,setPeople); const b=subscribeTodayAttendance(profile.department,setAttendance); return()=>{a();b()}},[profile?.department])
  const rows=useMemo(()=>people.map(p=>({...p,attendance:attendance.find(a=>a.uid===p.id)})).filter(p=>`${p.name} ${p.employeeId} ${p.email}`.toLowerCase().includes(search.toLowerCase())),[people,attendance,search])
  return <div className="mx-auto max-w-7xl"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-slate-500"><UsersRound size={16}/> {profile?.department}</div><h1 className="mt-1 text-3xl font-semibold tracking-tight">Department board</h1><p className="mt-2 text-sm text-slate-500">Everyone in your department can see the same live attendance status.</p></div><div className="relative sm:w-72"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search employee..." className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-slate-400 focus:ring-4 focus:ring-slate-100"/></div></div>
    <div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Employee</th><th className="px-6 py-4">Status</th><th className="px-6 py-4">Time In</th><th className="px-6 py-4">Time Out</th><th className="px-6 py-4">Duration</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map(p=><tr key={p.id} className="hover:bg-slate-50/80"><td className="px-6 py-4"><div className="font-semibold text-slate-900">{p.name}</div><div className="mt-0.5 text-xs text-slate-500">{p.employeeId} · {p.email}</div></td><td className="px-6 py-4"><StatusBadge status={p.attendance?.status}/></td><td className="px-6 py-4 text-sm font-medium text-slate-700">{formatTime(p.attendance?.timeIn)}</td><td className="px-6 py-4 text-sm font-medium text-slate-700">{formatTime(p.attendance?.timeOut)}</td><td className="px-6 py-4 text-sm text-slate-500">{p.attendance?.timeIn?humanDuration(minutesBetween(p.attendance.timeIn,p.attendance.timeOut)):'—'}</td></tr>)}</tbody></table>{rows.length===0&&<div className="p-12 text-center text-sm text-slate-500">No matching employees found.</div>}</div></div>
  </div>
}
