import { Clock3 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { subscribeMyAttendance } from '../services/attendance'
import { formatTime, humanDuration, minutesBetween } from '../utils/date'

export default function MyLogs() {
  const { user }=useAuth(); const [logs,setLogs]=useState([])
  useEffect(()=>user?.uid?subscribeMyAttendance(user.uid,setLogs):undefined,[user?.uid])
  const total=useMemo(()=>logs.reduce((sum,l)=>sum+minutesBetween(l.timeIn,l.timeOut),0),[logs])
  return <div className="mx-auto max-w-6xl"><div className="mb-6"><div className="flex items-center gap-2 text-sm font-semibold text-slate-500"><Clock3 size={16}/> Personal attendance</div><h1 className="mt-1 text-3xl font-semibold tracking-tight">My DTR logs</h1><p className="mt-2 text-sm text-slate-500">Your recorded Time In and Time Out history.</p></div><div className="mb-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">Records</div><div className="mt-2 text-3xl font-semibold">{logs.length}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="text-sm text-slate-500">Recorded hours</div><div className="mt-2 text-3xl font-semibold">{humanDuration(total)}</div></div></div><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left"><thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th className="px-6 py-4">Date</th><th className="px-6 py-4">Time In</th><th className="px-6 py-4">Time Out</th><th className="px-6 py-4">Total</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{logs.map(l=><tr key={l.id}><td className="px-6 py-4 font-semibold text-slate-900">{l.dateKey}</td><td className="px-6 py-4 text-sm">{formatTime(l.timeIn)}</td><td className="px-6 py-4 text-sm">{formatTime(l.timeOut)}</td><td className="px-6 py-4 text-sm text-slate-500">{humanDuration(minutesBetween(l.timeIn,l.timeOut))}</td><td className="px-6 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${l.status==='OUT'?'bg-slate-100 text-slate-700':'bg-emerald-50 text-emerald-700'}`}>{l.status==='OUT'?'Completed':'Active'}</span></td></tr>)}</tbody></table>{logs.length===0&&<div className="p-12 text-center text-sm text-slate-500">No DTR records yet.</div>}</div></div></div>
}
